network:
  version: 2
  ethernets:
    ens18:
      dhcp4: no
      addresses:
        - 10.0.0.1/24 
      nameservers:
        addresses:
          - 10.0.0.4 # our own dns server
          - 8.8.8.8     